import { Employee, Project } from "./types";

export const EMPLOYEES: Employee[] = [
  {
    id: "sk",
    name: "Sarah K.",
    initials: "SK",
    color: "#6366f1",
    role: "Senior Frontend Engineer",
    skills: ["React", "TypeScript", "CSS", "Auth"],
    status: "working",
    currentTask: "Auth Module",
    efficiencyScore: 97.2,
    workHoursToday: 6.5,
    breakMinutesToday: 18,
    deskId: "d1",
  },
  {
    id: "rp",
    name: "Raj P.",
    initials: "RP",
    color: "#8b5cf6",
    role: "Backend Engineer",
    skills: ["Node.js", "Python", "PostgreSQL", "API"],
    status: "working",
    currentTask: "API Endpoints",
    efficiencyScore: 94.8,
    workHoursToday: 6.0,
    breakMinutesToday: 22,
    deskId: "d2",
  },
  {
    id: "ad",
    name: "Ana D.",
    initials: "AD",
    color: "#ec4899",
    role: "Frontend Engineer",
    skills: ["React", "Vue", "CSS", "Figma"],
    status: "working",
    currentTask: "Frontend Refactor",
    efficiencyScore: 91.5,
    workHoursToday: 5.5,
    breakMinutesToday: 30,
    deskId: "d3",
  },
  {
    id: "mk",
    name: "Mike K.",
    initials: "MK",
    color: "#f59e0b",
    role: "DevOps Engineer",
    skills: ["Docker", "AWS", "CI/CD", "Kubernetes"],
    status: "meeting",
    currentTask: "Sprint Planning",
    efficiencyScore: 89.1,
    workHoursToday: 5.0,
    breakMinutesToday: 15,
    deskId: "d4",
  },
  {
    id: "js",
    name: "James S.",
    initials: "JS",
    color: "#10b981",
    role: "Full Stack Engineer",
    skills: ["React", "Node.js", "GraphQL", "API"],
    status: "break",
    currentTask: "Rate Limiting",
    efficiencyScore: 88.3,
    workHoursToday: 4.5,
    breakMinutesToday: 45,
    deskId: "d5",
  },
  {
    id: "lm",
    name: "Lisa M.",
    initials: "LM",
    color: "#f43f5e",
    role: "QA Engineer",
    skills: ["Testing", "Cypress", "Playwright", "QA"],
    status: "working",
    currentTask: "E2E Test Suite",
    efficiencyScore: 92.0,
    workHoursToday: 6.2,
    breakMinutesToday: 20,
    deskId: "d6",
  },
  {
    id: "ps",
    name: "Priya S.",
    initials: "PS",
    color: "#94a3b8",
    role: "Data Engineer",
    skills: ["Python", "SQL", "dbt", "Analytics"],
    status: "time-off",
    efficiencyScore: 87.5,
    workHoursToday: 0,
    breakMinutesToday: 0,
  },
  {
    id: "tm",
    name: "Tom M.",
    initials: "TM",
    color: "#06b6d4",
    role: "Mobile Engineer",
    skills: ["React Native", "iOS", "Android", "TypeScript"],
    status: "offline",
    efficiencyScore: 85.0,
    workHoursToday: 0,
    breakMinutesToday: 0,
  },
];

export const PROJECTS: Project[] = [
  {
    id: "p1",
    name: "Customer Portal v2",
    description:
      "Full redesign of the customer-facing portal with new auth, dashboard, and analytics.",
    progress: 62,
    status: "active",
    createdAt: "2026-01-15",
    teamIds: ["sk", "rp", "ad", "js"],
    tasks: [
      { id: "t1", title: "Setup authentication service", tag: "Backend", status: "done", assigneeId: "sk" },
      { id: "t2", title: "Design database schema", tag: "Database", status: "done", assigneeId: "rp" },
      { id: "t3", title: "Build login / signup UI", tag: "Frontend", status: "done", assigneeId: "ad" },
      { id: "t4", title: "Implement rate limiting", tag: "Backend", status: "in-progress", assigneeId: "js", estimatedHours: 4 },
      { id: "t5", title: "Add WebSocket handlers", tag: "Backend", status: "in-progress", assigneeId: "rp", estimatedHours: 6 },
      { id: "t6", title: "Dashboard analytics charts", tag: "Frontend", status: "todo", assigneeId: "ad", estimatedHours: 8 },
      { id: "t7", title: "Implement rate limiting cache layer", tag: "Backend", status: "ai-suggested", estimatedHours: 3 },
      { id: "t8", title: "Add real-time notifications", tag: "Full Stack", status: "ai-suggested", estimatedHours: 5 },
    ],
  },
  {
    id: "p2",
    name: "Internal Analytics Platform",
    description:
      "Build an internal data platform for tracking KPIs, team performance, and project health.",
    progress: 28,
    status: "active",
    createdAt: "2026-02-01",
    teamIds: ["ps", "rp", "lm"],
    tasks: [
      { id: "t9", title: "Data pipeline architecture", tag: "Data", status: "done", assigneeId: "ps" },
      { id: "t10", title: "ETL jobs for metrics", tag: "Data", status: "in-progress", assigneeId: "ps", estimatedHours: 10 },
      { id: "t11", title: "Metrics dashboard UI", tag: "Frontend", status: "todo", assigneeId: "ad", estimatedHours: 12 },
      { id: "t12", title: "Automated reporting emails", tag: "Backend", status: "ai-suggested", estimatedHours: 4 },
    ],
  },
  {
    id: "p3",
    name: "Mobile App — iOS & Android",
    description: "Native-feeling React Native app wrapping the core product for mobile users.",
    progress: 10,
    status: "planning",
    createdAt: "2026-02-18",
    teamIds: ["tm", "sk", "lm"],
    tasks: [
      { id: "t13", title: "Setup React Native project", tag: "Mobile", status: "done", assigneeId: "tm" },
      { id: "t14", title: "Auth screens", tag: "Mobile", status: "todo", assigneeId: "tm", estimatedHours: 6 },
      { id: "t15", title: "Push notification service", tag: "Backend", status: "ai-suggested", estimatedHours: 5 },
      { id: "t16", title: "Offline sync strategy", tag: "Mobile", status: "ai-suggested", estimatedHours: 8 },
    ],
  },
];

export const DESKS = [
  { id: "d1", label: "Desk 1" },
  { id: "d2", label: "Desk 2" },
  { id: "d3", label: "Desk 3" },
  { id: "d4", label: "Desk 4" },
  { id: "d5", label: "Desk 5" },
  { id: "d6", label: "Desk 6" },
  { id: "d7", label: "Open" },
  { id: "d8", label: "Open" },
  { id: "d9", label: "Open" },
];
